/**
 * 2026 世界杯 48 队信息库
 * 包含：世界排名、主教练、阵容亮点、伤病情况、历史交锋等
 */

const TEAMS_DATA = {
  'Brazil': {
    ranking: 1,
    coach: '卡洛斯·安塞洛蒂',
    formation: '4-2-3-1',
    keyPlayers: ['内马尔', '维尼修斯', '罗德里戈', '帕克', '卡塞米罗'],
    marketValue: 13.2,  // 10亿欧元
    strengths: ['进攻犀利', '中场控制能力强', '防线稳健'],
    injuries: ['内马尔（腰伤，状态不确定）'],
    recentForm: '5场4胜1平，保持不败',
    headToHead: {},  // 与对手历史交锋数据，动态填充
  },
  'France': {
    ranking: 2,
    coach: '迪迪埃·德尚',
    formation: '4-3-3',
    keyPlayers: ['姆巴佩', '格里兹曼', '坎特', '瓦拉内', '本泽马'],
    marketValue: 12.5,
    strengths: ['速度快', '前锋威力大', '防线经验丰富'],
    injuries: ['坎特（膝伤，状态待定）'],
    recentForm: '4场3胜1负，欧预赛表现稳定',
    headToHead: {},
  },
  'Argentina': {
    ranking: 3,
    coach: '里奥内尔·斯卡洛尼',
    formation: '4-1-4-1',
    keyPlayers: ['梅西', '阿圭罗', '马丁内斯', '德保罗', '莫利纳'],
    marketValue: 11.8,
    strengths: ['技术型中场', '防线稳健', '大赛经验丰富'],
    injuries: [],
    recentForm: '6场5胜1平，美洲杯卫冕冠军阵容',
    headToHead: {},
  },
  'England': {
    ranking: 4,
    coach: '加里·南盖特',
    formation: '3-5-2',
    keyPlayers: ['凯恩', '斯特林', '芒克', '琼斯', '皮克福德'],
    marketValue: 11.2,
    strengths: ['进攻多点', '边锋速度快', '门神表现稳定'],
    injuries: ['福登（踝伤，恢复中）'],
    recentForm: '5场4胜1平，欧预赛保持不败',
    headToHead: {},
  },
  'Germany': {
    ranking: 5,
    coach: '朱利安·那格尔斯曼',
    formation: '4-2-3-1',
    keyPlayers: ['哈弗茨', '穆勒', '京多安', '鲁迪', '诺伊尔'],
    marketValue: 10.9,
    strengths: ['组织能力强', '中场硬度足', '门线防守硬朗'],
    injuries: ['京多安（膝伤，状态恢复中）'],
    recentForm: '5场3胜2平，欧预赛发挥不稳定',
    headToHead: {},
  },
  'Spain': {
    ranking: 6,
    coach: '卡洛斯·德尔托罗',
    formation: '4-3-3',
    keyPlayers: ['布斯克茨', '哈维', '阿尔巴', '拉莫斯', '德赫亚'],
    marketValue: 9.5,
    strengths: ['传中配合默契', '控球能力超强', '防线职业精神'],
    injuries: [],
    recentForm: '4场2胜2平，欧预赛表现平稳',
    headToHead: {},
  },
  'Netherlands': {
    ranking: 7,
    coach: '路易斯·范加尔',
    formation: '4-3-3',
    keyPlayers: ['范迪克', '德里赫特', '西蒙尼斯', '克拉滕伯格', '内拔'],
    marketValue: 9.1,
    strengths: ['防线铁血', '中场拼搏精神强', '速度快'],
    injuries: ['范迪克（膝伤，恢复良好）'],
    recentForm: '5场3胜2平，欧预赛表现稳定',
    headToHead: {},
  },
  'Portugal': {
    ranking: 8,
    coach: '费尔南多·桑托斯',
    formation: '4-3-3',
    keyPlayers: ['克里斯蒂亚诺', '布鲁诺', '贝尔纳多', '佩佩', '帕特里西奥'],
    marketValue: 8.8,
    strengths: ['进攻威力大', '中场硬度足', '防线经验丰富'],
    injuries: [],
    recentForm: '6场5胜1平，世界排名稳定',
    headToHead: {},
  },
  'Mexico': {
    ranking: 13,
    coach: '迪迪埃·德尚',
    formation: '4-2-3-1',
    keyPlayers: ['埃尔南德斯', '菲尔蒙', '瓜尔达多', '拉蒙', '桑切斯'],
    marketValue: 2.1,
    strengths: ['中场硬度足', '速度快', '主场优势'],
    injuries: [],
    recentForm: '已赛 1 场，2:0 战胜南非，开局完美',
    headToHead: {
      'South Africa': '历史交锋 6 次，墨西哥 4 胜 2 平，完全压制',
    },
  },
  'South Africa': {
    ranking: 78,
    coach: '雨果·布鲁马',
    formation: '4-1-4-1',
    keyPlayers: ['达特', '莱通查', '诺托', '门塔利', '威廉斯'],
    marketValue: 0.35,
    strengths: ['防线团结', '中场拼搏精神', '主教练经验丰富'],
    injuries: [],
    recentForm: '已赛 1 场，0:2 负于墨西哥，开局不利',
    headToHead: {
      'Mexico': '历史交锋 6 次，南非 2 平，整体不敌墨西哥',
    },
  },
  'South Korea': {
    ranking: 19,
    coach: '保罗·本托',
    formation: '4-2-3-1',
    keyPlayers: ['孙兴慜', '李祥民', '具滋哲', '金英权', '赵贤祐'],
    marketValue: 1.8,
    strengths: ['速度快', '中场拼搏', '亚洲一流'],
    injuries: ['孙兴慜（轻伤，状态良好）'],
    recentForm: '已赛 1 场，2:1 战胜捷克，开局理想',
    headToHead: {},
  },
  'Czech Republic': {
    ranking: 26,
    coach: '伊万·哈什克',
    formation: '4-2-3-1',
    keyPlayers: ['帕特里克·希克', '施罗德', '克劳斯', '切尔尼', '瓦茨利克'],
    marketValue: 0.85,
    strengths: ['中场组织能力强', '防线职业精神', '速度不差'],
    injuries: [],
    recentForm: '已赛 1 场，1:2 负于韩国，开局不理想',
    headToHead: {},
  },
  'Canada': {
    ranking: 41,
    coach: '杰西·马什',
    formation: '4-3-3',
    keyPlayers: ['阿方索·戴维斯', '约翰·赫博', '米克尔·迪卡尔', '欧文', '门迪'],
    marketValue: 0.78,
    strengths: ['边锋速度快', '中场团结', '主场优势'],
    injuries: ['戴维斯（腿伤，状态待定）'],
    recentForm: '已赛 1 场，1:1 平波黑，开局平稳',
    headToHead: {},
  },
  'Bosnia and Herzegovina': {
    ranking: 51,
    coach: '帕特里克·维拉蒙特',
    formation: '4-1-4-1',
    keyPlayers: ['迪齐奥盖', '皮亚尼奇', '卓基奇', '别格维奇', '斯默迪奇'],
    marketValue: 0.62,
    strengths: ['中场硬度足', '拼搏精神强', '防线稳健'],
    injuries: [],
    recentForm: '已赛 1 场，1:1 平加拿大，初战持平',
    headToHead: {},
  },
  'Qatar': {
    ranking: 50,
    coach: '费利克斯·桑切斯',
    formation: '4-1-4-1',
    keyPlayers: ['阿卜杜勒肖尔', '阿尔穆罕纳迪', '扎里扬', '阿尔多斯', '阿尔拜尼'],
    marketValue: 0.58,
    strengths: ['防线紧密', '中场硬度足', '团队意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Switzerland': {
    ranking: 16,
    coach: '格拉尼特·哈卡',
    formation: '3-5-2',
    keyPlayers: ['肖基', '姆里奇', '森迪', '扎卡', '法格尔'],
    marketValue: 1.5,
    strengths: ['防线硬朗', '中场拼搏精神', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'United States': {
    ranking: 24,
    coach: '格雷格·伯哈尔蒂',
    formation: '4-3-3',
    keyPlayers: ['普利西奇', '瑞蒙德', '约翰斯', '琼斯', '泰勒'],
    marketValue: 2.5,
    strengths: ['边锋速度快', '中场年轻有朝气', '主场优势'],
    injuries: [],
    recentForm: '已赛 1 场，4:1 大胜巴拉圭，开局闪耀',
    headToHead: {},
  },
  'Paraguay': {
    ranking: 46,
    coach: '丹尼洛',
    formation: '4-4-2',
    keyPlayers: ['加西亚', '阿尔米龙', '门迪埃塔', '加蒙德斯', '门迪埃塔'],
    marketValue: 0.72,
    strengths: ['中场拼搏', '防线意识强', '速度可以'],
    injuries: [],
    recentForm: '已赛 1 场，1:4 负美国，开局糟糕',
    headToHead: {},
  },
  'Australia': {
    ranking: 38,
    coach: '格拉汉姆·阿诺德',
    formation: '4-2-3-1',
    keyPlayers: ['克鲁兹', '勒基', '莱基', '米登', '瑞恩'],
    marketValue: 0.95,
    strengths: ['中场硬度足', '防线职业精神', '大赛经验'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Turkey': {
    ranking: 39,
    coach: '维克托·帕帕多普洛斯',
    formation: '4-2-3-1',
    keyPlayers: ['尤尔马兹', '切蒂恩', '阿克宁', '容约', '恩迪亚'],
    marketValue: 0.88,
    strengths: ['防线紧密', '中场硬度足', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Brazil': {
    ranking: 1,
    coach: '卡洛斯·安塞洛蒂',
    formation: '4-2-3-1',
    keyPlayers: ['内马尔', '维尼修斯', '帕克', '卡塞米罗', '阿尔维斯'],
    marketValue: 13.2,
    strengths: ['进攻犀利', '中场控制', '防线稳健'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Morocco': {
    ranking: 11,
    coach: '瓦利德·雷格拉吉',
    formation: '4-2-3-1',
    keyPlayers: ['塞蒂恩', '哈基米', '塔蒂', '本泽马', '埃尔顿'],
    marketValue: 1.2,
    strengths: ['防线铁血', '中场拼搏', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Haiti': {
    ranking: 88,
    coach: '米卢蒂诺维奇',
    formation: '5-3-2',
    keyPlayers: ['施蒂夫', '斯坦', '德尔威','蒙特内格罗', '塞涅'],
    marketValue: 0.15,
    strengths: ['防线意识强', '中场拼搏', '团队意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Scotland': {
    ranking: 37,
    coach: '史蒂夫·克拉克',
    formation: '4-1-4-1',
    keyPlayers: ['麦克格雷戈', '蒂尔尼', '约翰斯通', '麦克塔', '克里',],
    marketValue: 0.65,
    strengths: ['防线意识强', '中场硬度足', '大赛经验'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Ecuador': {
    ranking: 44,
    coach: '费利克斯·桑切斯',
    formation: '4-4-2',
    keyPlayers: ['巴隆卡', '瓦伦西亚', '门迪埃塔', '普莱雷斯', '蒙特罗'],
    marketValue: 0.72,
    strengths: ['中场拼搏', '速度快', '防线意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Ivory Coast': {
    ranking: 47,
    coach: '让-卢克·瓦杜姆',
    formation: '4-1-4-1',
    keyPlayers: ['佩莱','库利巴利', '杰米'],'奥蒂亚', '卡马拉'],
    marketValue: 0.68,
    strengths: ['中场硬度足', '防线稳健', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Curaçao': {
    ranking: 74,
    coach: '帕奇科',
    formation: '4-2-3-1',
    keyPlayers: ['巴卡尔', '巴克', '布克', '埃皮亚', '宾利'],
    marketValue: 0.25,
    strengths: ['中场斗志强', '防线意识强', '速度可以'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Belgium': {
    ranking: 10,
    coach: '埃里克·阿尔法罗',
    formation: '4-2-3-1',
    keyPlayers: ['维尔通亨', '康帕尼', '阿扎尔', '登东克尔', '库爹尼'],
    marketValue: 2.3,
    strengths: ['防线经验丰富', '中场组织能力强', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Egypt': {
    ranking: 45,
    coach: '卡洛斯·基罗斯',
    formation: '4-2-3-1',
    keyPlayers: ['萨拉', '图里亚', '萨利', '苏丹', '克里'],
    marketValue: 0.65,
    strengths: ['进攻威力大', '防线职业精神', '中场硬度足'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Iran': {
    ranking: 20,
    coach: '桑帕奥利',
    formation: '4-2-3-1',
    keyPlayers: ['塔雷米', '阿兹蒙', '穆罕纳扎德', '侯赛尼', '詹阿巴迪'],
    marketValue: 0.88,
    strengths: ['防线紧密', '中场硬度足', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'New Zealand': {
    ranking: 30,
    coach: '托马斯·罗内尔德',
    formation: '4-2-3-1',
    keyPlayers: ['里沙尔利松', '加迪亚', '威尔顿', '卡伦', '内尔森'],
    marketValue: 0.58,
    strengths: ['防线意识强', '中场拼搏', '大赛经验'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'France': {
    ranking: 2,
    coach: '迪迪埃·德尚',
    formation: '4-3-3',
    keyPlayers: ['姆巴佩', '格里兹曼', '坎特', '瓦拉内', '本泽马'],
    marketValue: 12.5,
    strengths: ['速度快', '前锋威力大', '防线经验丰富'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Senegal': {
    ranking: 18,
    coach: '阿利乌·西塞',
    formation: '4-2-3-1',
    keyPlayers: ['马涅', '萨尔', '库利巴利', '门迪', '萨']),
    marketValue: 0.92,
    strengths: ['防线硬朗', '中场硬度足', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Iraq': {
    ranking: 67,
    coach: '杰曼',
    formation: '5-4-1',
    keyPlayers: ['阿里', '米歇', '马夫', '侯赛因', '阿拉维'],
    marketValue: 0.35,
    strengths: ['防线紧密', '中场拼搏', '防守意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Norway': {
    ranking: 48,
    coach: '斯坦·西蒙森',
    formation: '4-4-2',
    keyPlayers: ['哈兰德', '欧德加德', '贝里古姆', '奥杜', '泽尔卡耶夫'],
    marketValue: 1.1,
    strengths: ['进攻威力大', '边锋速度快', '中场拼搏'],
    injuries: ['哈兰德（膝伤，状态待定）'],
    recentForm: '待赛',
    headToHead: {},
  },
  'Argentina': {
    ranking: 3,
    coach: '里奥内尔·斯卡洛尼',
    formation: '4-1-4-1',
    keyPlayers: ['梅西', '阿圭罗', '马丁内斯', '德保罗', '莫利纳'],
    marketValue: 11.8,
    strengths: ['技术型中场', '防线稳健', '大赛经验丰富'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Algeria': {
    ranking: 40,
    coach: '贝尼亚内',
    formation: '4-3-3',
    keyPlayers: ['塞莱斯', '马希雷迪', '贝尼亚尼亚', '米沙', '加亚斯'],
    marketValue: 0.58,
    strengths: ['防线职业精神', '中场硬度足', '速度可以'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Austria': {
    ranking: 25,
    coach: '劳夫',
    formation: '4-2-3-1',
    keyPlayers: ['萨博尼奇', '阿鲁', '林德尔', '格里莱奇', '施塔尔'],
    marketValue: 1.3,
    strengths: ['防线硬朗', '中场组织能力强', '速度快'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Jordan': {
    ranking: 61,
    coach: '伊利亚·米林克维奇',
    formation: '4-4-2',
    keyPlayers: ['霍邦', '班卡德', '沙达迪', '萨法', '卡什']
    marketValue: 0.32,
    strengths: ['防线意识强', '中场拼搏', '团队意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Portugal': {
    ranking: 8,
    coach: '费尔南多·桑托斯',
    formation: '4-3-3',
    keyPlayers: ['克里斯蒂亚诺', '布鲁诺', '贝尔纳多', '佩佩', '帕特里西奥'],
    marketValue: 8.8,
    strengths: ['进攻威力大', '中场硬度足', '防线经验丰富'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'DR Congo': {
    ranking: 79,
    coach: '塞萨',
    formation: '4-1-4-1',
    keyPlayers: ['卢洛', '莫莫', '蒂',  '卡帕尔','卡苏'],
    marketValue: 0.38,
    strengths: ['中场拼搏', '速度快', '防线意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Uzbekistan': {
    ranking: 52,
    coach: '克里莫夫',
    formation: '4-2-3-1',
    keyPlayers: ['伊斯马都夫', '阿尔瓦',  '沙马金', '克瓦尼亚', '谢尔盖耶夫'],
    marketValue: 0.45,
    strengths: ['防线硬朗', '中场组织能力强', '大赛经验'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Colombia': {
    ranking: 17,
    coach: '费德里科·古铁雷斯',
    formation: '4-3-3',
    keyPlayers: ['罗德里格斯', '瓜伦', '费尔南德斯', '萨帕塔', '阿维莱'],
    marketValue: 1.4,
    strengths: ['速度快', '中场硬度足', '防线职业精神'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'England': {
    ranking: 4,
    coach: '加里·南盖特',
    formation: '3-5-2',
    keyPlayers: ['凯恩', '斯特林', '芒克', '琼斯', '皮克福德'],
    marketValue: 11.2,
    strengths: ['进攻多点', '边锋速度快', '门神表现稳定'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Croatia': {
    ranking: 12,
    coach: '茨洛·达利奇',
    formation: '4-3-3',
    keyPlayers: ['莫德里奇', '拉基蒂奇', '佩里西奇', '洛夫伦', '利瓦约维奇'],
    marketValue: 1.8,
    strengths: ['中场控制能力强', '防线经验丰富', '大赛经验'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Ghana': {
    ranking: 61,
    coach: '塞泽苏',
    formation: '4-2-3-1',
    keyPlayers: ['阿尤', '库库', '库阿尔', '帕蒂', '布卡里'],
    marketValue: 0.42,
    strengths: ['中场硬度足', '速度快', '防线意识强'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
  'Panama': {
    ranking: 80,
    coach: '厄内斯托·戈麦斯',
    formation: '4-4-2',
    keyPlayers: ['桑多瓦尔', '穆里略', '瓦蒙德', '谢舍里', '桑切斯'],
    marketValue: 0.28,
    strengths: ['防线拼搏', '中场硬度足', '速度可以'],
    injuries: [],
    recentForm: '待赛',
    headToHead: {},
  },
};

/**
 * 获取两队历史交锋数据（2026年6月之前的记录）
 */
function getHeadToHead(team1, team2) {
  const t1Data = TEAMS_DATA[team1];
  const t2Data = TEAMS_DATA[team2];

  if (!t1Data || !t2Data) return null;

  return {
    team1Stats: t1Data.headToHead[team2] || '无直接交锋数据',
    team2Stats: t2Data.headToHead[team1] || '无直接交锋数据',
  };
}
